<?php
$xmlstr = <<<XML
<ArrayOfMAS_RECIPE xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.datacontract.org/2004/07/FDA_RESTFULL_CENTER">
<MAS_RECIPE>
<ADDR>23 </ADDR>
<AMPHRNM>ทวีวัฒนา</AMPHRNM>
<APPROVE_DATE>2019-07-08T00:00:00</APPROVE_DATE>
<CHNGWTNM>กรุงเทพมหานคร</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>โรงพยาบาลเจ้าพระยาอภัยภูเบศร</LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>10/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>8</MU>
<REGISTER_CODE>SAS1</REGISTER_CODE>
<REGISTER_FORMAT>น้ำมันกัญชาหยดใต้ลิ้น</REGISTER_FORMAT>
<REGISTER_IDA>1</REGISTER_IDA>
<REGISTER_NAME>กัญชา</REGISTER_NAME>
<REGISTER_PACKAGE>5 </REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ขวด</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>
ผลิตภัณฑ์กัญชานี้ได้รับยกเว้นการรับรองตำรับจากสำนักงาน อย. เพื่อใช้สำหรับผู้ป่วยเฉพาะราย ภายใต้รูปแบบพิเศษของการเข้าถึงยา ( Special access scheme ) ต้องสั่งจ่ายโดยแพทย์ที่ผ่านการอบรมหลักสูตรการใช้กัญชาและสารสกัดจากกัญชาในทางการแพทย์จากกระทรวงสาธารณสุขและต้องได้รับการยินยอมจากผู้ป่วยหรือผู้ดูแลผู้ป่วย โดยการลงนามเป็นลายลักษณ์อักษรในเอกสารแสดงความยินยอม
</REGISTER_REMARK>
<REGISTER_STRENGTH>THC 1.7% W/V (THC 0.5mg/drop)</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>น้ำมันกัญชาหยอดใต้ลิ้น </REGISTER_TRADER_NAME>
<REGISTER_TYPE>2</REGISTER_TYPE>
<REGISTER_UNIT>ml</REGISTER_UNIT>
<ROAD>พุทธมณฑลสาย 4</ROAD>
<SOI>-</SOI>
<TEL>0 2441 6100</TEL>
<THMBLNM>ทวีวัฒนา</THMBLNM>
<ZIPCODE>10170</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>2</ADDR>
<AMPHRNM>สาทร</AMPHRNM>
<APPROVE_DATE>2019-01-11T00:00:00</APPROVE_DATE>
<CHNGWTNM>กรุงเทพมหานคร</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>องค์การเภสัชกรรม</LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>8/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>SAS2</REGISTER_CODE>
<REGISTER_FORMAT>น้ำมันกัญชาหยดใต้ลิ้น</REGISTER_FORMAT>
<REGISTER_IDA>2</REGISTER_IDA>
<REGISTER_NAME>กัญชา </REGISTER_NAME>
<REGISTER_PACKAGE>10</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ขวด</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>
ผลิตภัณฑ์กัญชานี้ได้รับยกเว้นการรับรองตำรับจากสำนักงาน อย. เพื่อใช้สำหรับผู้ป่วยเฉพาะราย ภายใต้รูปแบบพิเศษของการเข้าถึงยา ( Special access scheme ) ต้องสั่งจ่ายโดยแพทย์ที่ผ่านการอบรมหลักสูตรการใช้กัญชาและสารสกัดจากกัญชาในทางการแพทย์จากกระทรวงสาธารณสุขและต้องได้รับการยินยอมจากผู้ป่วยหรือผู้ดูแลผู้ป่วย โดยการลงนามเป็นลายลักษณ์อักษรในเอกสารแสดงความยินยอม
</REGISTER_REMARK>
<REGISTER_STRENGTH>CBD 100 mg/ml</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>GPO CBD </REGISTER_TRADER_NAME>
<REGISTER_TYPE>2</REGISTER_TYPE>
<REGISTER_UNIT>ml</REGISTER_UNIT>
<ROAD>นราธิวาสราชนครินทร์</ROAD>
<SOI>-</SOI>
<TEL>0 2676 2727</TEL>
<THMBLNM>ทุ่งวัดดอน</THMBLNM>
<ZIPCODE>10120</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>2</ADDR>
<AMPHRNM>สาทร</AMPHRNM>
<APPROVE_DATE>2019-01-11T00:00:00</APPROVE_DATE>
<CHNGWTNM>กรุงเทพมหานคร</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>องค์การเภสัชกรรม</LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>8/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>SAS3</REGISTER_CODE>
<REGISTER_FORMAT>น้ำมันกัญชาหยดใต้ลิ้น</REGISTER_FORMAT>
<REGISTER_IDA>3</REGISTER_IDA>
<REGISTER_NAME>กัญชา </REGISTER_NAME>
<REGISTER_PACKAGE>5</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ขวด</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>
ผลิตภัณฑ์กัญชานี้ได้รับยกเว้นการรับรองตำรับจากสำนักงาน อย. เพื่อใช้สำหรับผู้ป่วยเฉพาะราย ภายใต้รูปแบบพิเศษของการเข้าถึงยา ( Special access scheme ) ต้องสั่งจ่ายโดยแพทย์ที่ผ่านการอบรมหลักสูตรการใช้กัญชาและสารสกัดจากกัญชาในทางการแพทย์จากกระทรวงสาธารณสุขและต้องได้รับการยินยอมจากผู้ป่วยหรือผู้ดูแลผู้ป่วย โดยการลงนามเป็นลายลักษณ์อักษรในเอกสารแสดงความยินยอม
</REGISTER_REMARK>
<REGISTER_STRENGTH>THC 27 mg/mL, CBD 25 mg/ml</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>GPO THC:CBD(1:1)</REGISTER_TRADER_NAME>
<REGISTER_TYPE>2</REGISTER_TYPE>
<REGISTER_UNIT>ml</REGISTER_UNIT>
<ROAD>นราธิวาสราชนครินทร์</ROAD>
<SOI>-</SOI>
<TEL>0 2676 2727</TEL>
<THMBLNM>ทุ่งวัดดอน</THMBLNM>
<ZIPCODE>10120</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>2</ADDR>
<AMPHRNM>สาทร</AMPHRNM>
<APPROVE_DATE>2019-01-11T00:00:00</APPROVE_DATE>
<CHNGWTNM>กรุงเทพมหานคร</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>องค์การเภสัชกรรม</LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>8/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>SAS4</REGISTER_CODE>
<REGISTER_FORMAT>น้ำมันกัญชาหยดใต้ลิ้น</REGISTER_FORMAT>
<REGISTER_IDA>4</REGISTER_IDA>
<REGISTER_NAME>กัญชา </REGISTER_NAME>
<REGISTER_PACKAGE>5</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ขวด</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>
ผลิตภัณฑ์กัญชานี้ได้รับยกเว้นการรับรองตำรับจากสำนักงาน อย. เพื่อใช้สำหรับผู้ป่วยเฉพาะราย ภายใต้รูปแบบพิเศษของการเข้าถึงยา ( Special access scheme ) ต้องสั่งจ่ายโดยแพทย์ที่ผ่านการอบรมหลักสูตรการใช้กัญชาและสารสกัดจากกัญชาในทางการแพทย์จากกระทรวงสาธารณสุขและต้องได้รับการยินยอมจากผู้ป่วยหรือผู้ดูแลผู้ป่วย โดยการลงนามเป็นลายลักษณ์อักษรในเอกสารแสดงความยินยอม
</REGISTER_REMARK>
<REGISTER_STRENGTH>THC 0.5 mg/drop</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>GPO THC</REGISTER_TRADER_NAME>
<REGISTER_TYPE>2</REGISTER_TYPE>
<REGISTER_UNIT>ml</REGISTER_UNIT>
<ROAD>นราธิวาสราชนครินทร์</ROAD>
<SOI>-</SOI>
<TEL>0 2676 2727</TEL>
<THMBLNM>ทุ่งวัดดอน</THMBLNM>
<ZIPCODE>10120</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>38 </ADDR>
<AMPHRNM>เมืองนนทบุรี</AMPHRNM>
<APPROVE_DATE>2019-07-08T00:00:00</APPROVE_DATE>
<CHNGWTNM>นนทบุรี</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>โรงพยาบาลพระอาจารย์ฝั้น อาจาโร </LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>11/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>TP1</REGISTER_CODE>
<REGISTER_FORMAT>ยาผง</REGISTER_FORMAT>
<REGISTER_IDA>5</REGISTER_IDA>
<REGISTER_NAME>กัญชา</REGISTER_NAME>
<REGISTER_PACKAGE>3.75</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ซอง</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>เป็นผลิตภัณฑ์กัญชาตำรับแผนไทย</REGISTER_REMARK>
<REGISTER_STRENGTH>กัญชา1กรัมในผงยา27กรัม</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>ยาอัคคินีวคณะ อาจาโร เฮิร์บ</REGISTER_TRADER_NAME>
<REGISTER_TYPE>1</REGISTER_TYPE>
<REGISTER_UNIT>g/sachet</REGISTER_UNIT>
<ROAD>ติวานนท์</ROAD>
<SOI>ติวานนท์ 14</SOI>
<TEL>0 2590 3474</TEL>
<THMBLNM>ตลาดขวัญ</THMBLNM>
<ZIPCODE>11000</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>38 </ADDR>
<AMPHRNM>เมืองนนทบุรี</AMPHRNM>
<APPROVE_DATE>2019-07-08T00:00:00</APPROVE_DATE>
<CHNGWTNM>นนทบุรี</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>โรงพยาบาลพระอาจารย์ฝั้น อาจาโร </LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>11/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>TP2</REGISTER_CODE>
<REGISTER_FORMAT>ยาผง</REGISTER_FORMAT>
<REGISTER_IDA>6</REGISTER_IDA>
<REGISTER_NAME>กัญชา</REGISTER_NAME>
<REGISTER_PACKAGE>2</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ซอง</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>เป็นผลิตภัณฑ์กัญชาตำรับแผนไทย</REGISTER_REMARK>
<REGISTER_STRENGTH>กัญชา12กรัมในผงยา78กรัม</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>ยาศุขไสยาศน์ อาจาโร เฮิร์บ</REGISTER_TRADER_NAME>
<REGISTER_TYPE>1</REGISTER_TYPE>
<REGISTER_UNIT>g/sachet</REGISTER_UNIT>
<ROAD>ติวานนท์</ROAD>
<SOI>ติวานนท์ 14</SOI>
<TEL>0 2590 3474</TEL>
<THMBLNM>ตลาดขวัญ</THMBLNM>
<ZIPCODE>11000</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>38 </ADDR>
<AMPHRNM>เมืองนนทบุรี</AMPHRNM>
<APPROVE_DATE>2019-07-08T00:00:00</APPROVE_DATE>
<CHNGWTNM>นนทบุรี</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>โรงพยาบาลพระอาจารย์ฝั้น อาจาโร </LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>11/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>TP3</REGISTER_CODE>
<REGISTER_FORMAT>ยาผง</REGISTER_FORMAT>
<REGISTER_IDA>7</REGISTER_IDA>
<REGISTER_NAME>กัญชา </REGISTER_NAME>
<REGISTER_PACKAGE>3.75</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ซอง</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>เป็นผลิตภัณฑ์กัญชาตำรับแผนไทย</REGISTER_REMARK>
<REGISTER_STRENGTH>กัญชา1กรัมในผงยา12กรัม</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>ยาแก้ลมเนาวนารีวาโย อาจาโร เฮิร์บ</REGISTER_TRADER_NAME>
<REGISTER_TYPE>1</REGISTER_TYPE>
<REGISTER_UNIT>g/sachet</REGISTER_UNIT>
<ROAD>ติวานนท์</ROAD>
<SOI>ติวานนท์ 14</SOI>
<TEL>0 2590 3474</TEL>
<THMBLNM>ตลาดขวัญ</THMBLNM>
<ZIPCODE>11000</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>38 </ADDR>
<AMPHRNM>เมืองนนทบุรี</AMPHRNM>
<APPROVE_DATE>2019-07-08T00:00:00</APPROVE_DATE>
<CHNGWTNM>นนทบุรี</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>โรงพยาบาลพระอาจารย์ฝั้น อาจาโร </LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>11/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>TP4</REGISTER_CODE>
<REGISTER_FORMAT>น้ำมัน</REGISTER_FORMAT>
<REGISTER_IDA>8</REGISTER_IDA>
<REGISTER_NAME>กัญชา </REGISTER_NAME>
<REGISTER_PACKAGE>60</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ขวด</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>เป็นผลิตภัณฑ์กัญชาตำรับแผนไทย</REGISTER_REMARK>
<REGISTER_STRENGTH>กัญชา1กิโลกรัมในน้ำมันงา1ลิตร</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>ยาน้ำมันสนั่นไตรภพ อาจาโร เฮิร์บ</REGISTER_TRADER_NAME>
<REGISTER_TYPE>1</REGISTER_TYPE>
<REGISTER_UNIT>ml/bottle</REGISTER_UNIT>
<ROAD>ติวานนท์</ROAD>
<SOI>ติวานนท์ 14</SOI>
<TEL>0 2590 3474</TEL>
<THMBLNM>ตลาดขวัญ</THMBLNM>
<ZIPCODE>11000</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>38 </ADDR>
<AMPHRNM>เมืองนนทบุรี</AMPHRNM>
<APPROVE_DATE>2019-07-08T00:00:00</APPROVE_DATE>
<CHNGWTNM>นนทบุรี</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>โรงพยาบาลพระอาจารย์ฝั้น อาจาโร </LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>11/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>TP5</REGISTER_CODE>
<REGISTER_FORMAT>ยาผง</REGISTER_FORMAT>
<REGISTER_IDA>9</REGISTER_IDA>
<REGISTER_NAME>กัญชา </REGISTER_NAME>
<REGISTER_PACKAGE>3</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ซอง</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>เป็นผลิตภัณฑ์กัญชาตำรับแผนไทย</REGISTER_REMARK>
<REGISTER_STRENGTH>กัญชา4กรัมในผงยา198กรัม</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>ยาแก้ลมขึ้นเบื้องสูง อาจาโร เฮิร์บ</REGISTER_TRADER_NAME>
<REGISTER_TYPE>1</REGISTER_TYPE>
<REGISTER_UNIT>g/sachet</REGISTER_UNIT>
<ROAD>ติวานนท์</ROAD>
<SOI>ติวานนท์ 14</SOI>
<TEL>0 2590 3474</TEL>
<THMBLNM>ตลาดขวัญ</THMBLNM>
<ZIPCODE>11000</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>38 </ADDR>
<AMPHRNM>เมืองนนทบุรี</AMPHRNM>
<APPROVE_DATE>2019-07-08T00:00:00</APPROVE_DATE>
<CHNGWTNM>นนทบุรี</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>โรงพยาบาลพระอาจารย์ฝั้น อาจาโร </LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>11/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>TP6</REGISTER_CODE>
<REGISTER_FORMAT>ยาผง</REGISTER_FORMAT>
<REGISTER_IDA>10</REGISTER_IDA>
<REGISTER_NAME>กัญชา </REGISTER_NAME>
<REGISTER_PACKAGE>2</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ซอง</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>เป็นผลิตภัณฑ์กัญชาตำรับแผนไทย</REGISTER_REMARK>
<REGISTER_STRENGTH>กัญชา1กรัมในผงยา104กรัม</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>ยาไฟอาวุธ อาจาโร เฮิร์บ</REGISTER_TRADER_NAME>
<REGISTER_TYPE>1</REGISTER_TYPE>
<REGISTER_UNIT>g/sachet</REGISTER_UNIT>
<ROAD>ติวานนท์</ROAD>
<SOI>ติวานนท์ 14</SOI>
<TEL>0 2590 3474</TEL>
<THMBLNM>ตลาดขวัญ</THMBLNM>
<ZIPCODE>11000</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>38 </ADDR>
<AMPHRNM>เมืองนนทบุรี</AMPHRNM>
<APPROVE_DATE>2019-07-08T00:00:00</APPROVE_DATE>
<CHNGWTNM>นนทบุรี</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>โรงพยาบาลพระอาจารย์ฝั้น อาจาโร </LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>11/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>TP7</REGISTER_CODE>
<REGISTER_FORMAT>ยาผง</REGISTER_FORMAT>
<REGISTER_IDA>11</REGISTER_IDA>
<REGISTER_NAME>กัญชา </REGISTER_NAME>
<REGISTER_PACKAGE>2.5</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ซอง</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>เป็นผลิตภัณฑ์กัญชาตำรับแผนไทย</REGISTER_REMARK>
<REGISTER_STRENGTH>ใบกัญชา8กรัมในผงยา16กรัม</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>ยาแก้นอนไม่หลับ/ยาแก้ไข้ผอมเหลือง อาจาโร เฮิร์บ</REGISTER_TRADER_NAME>
<REGISTER_TYPE>1</REGISTER_TYPE>
<REGISTER_UNIT>g/sachet</REGISTER_UNIT>
<ROAD>ติวานนท์</ROAD>
<SOI>ติวานนท์ 14</SOI>
<TEL>0 2590 3474</TEL>
<THMBLNM>ตลาดขวัญ</THMBLNM>
<ZIPCODE>11000</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>38 </ADDR>
<AMPHRNM>เมืองนนทบุรี</AMPHRNM>
<APPROVE_DATE>2019-07-08T00:00:00</APPROVE_DATE>
<CHNGWTNM>นนทบุรี</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>โรงพยาบาลพระอาจารย์ฝั้น อาจาโร </LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>11/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>TP8</REGISTER_CODE>
<REGISTER_FORMAT>ยาผง</REGISTER_FORMAT>
<REGISTER_IDA>12</REGISTER_IDA>
<REGISTER_NAME>กัญชา </REGISTER_NAME>
<REGISTER_PACKAGE>2</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ซอง</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>เป็นผลิตภัณฑ์กัญชาตำรับแผนไทย</REGISTER_REMARK>
<REGISTER_STRENGTH>กัญชา1กรัมในผงยา21กรัม</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>ยาแก้สันฑฆาต กล่อนแห้ง อาจาโร เฮิร์บ</REGISTER_TRADER_NAME>
<REGISTER_TYPE>1</REGISTER_TYPE>
<REGISTER_UNIT>g/sachet</REGISTER_UNIT>
<ROAD>ติวานนท์</ROAD>
<SOI>ติวานนท์ 14</SOI>
<TEL>0 2590 3474</TEL>
<THMBLNM>ตลาดขวัญ</THMBLNM>
<ZIPCODE>11000</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>38 </ADDR>
<AMPHRNM>เมืองนนทบุรี</AMPHRNM>
<APPROVE_DATE>2019-07-08T00:00:00</APPROVE_DATE>
<CHNGWTNM>นนทบุรี</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>โรงพยาบาลพระอาจารย์ฝั้น อาจาโร </LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>11/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>TP9</REGISTER_CODE>
<REGISTER_FORMAT>ยาผง</REGISTER_FORMAT>
<REGISTER_IDA>13</REGISTER_IDA>
<REGISTER_NAME>กัญชา </REGISTER_NAME>
<REGISTER_PACKAGE>1</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ซอง</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>เป็นผลิตภัณฑ์กัญชาตำรับแผนไทย</REGISTER_REMARK>
<REGISTER_STRENGTH>กัญชา10กรัมในผงยา76กรัม</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>ยาอัมฤตย์โอสถ อาจาโร เฮิร์บ</REGISTER_TRADER_NAME>
<REGISTER_TYPE>1</REGISTER_TYPE>
<REGISTER_UNIT>g/sachet</REGISTER_UNIT>
<ROAD>ติวานนท์</ROAD>
<SOI>ติวานนท์ 14</SOI>
<TEL>0 2590 3474</TEL>
<THMBLNM>ตลาดขวัญ</THMBLNM>
<ZIPCODE>11000</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>38 </ADDR>
<AMPHRNM>เมืองนนทบุรี</AMPHRNM>
<APPROVE_DATE>2019-07-08T00:00:00</APPROVE_DATE>
<CHNGWTNM>นนทบุรี</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>โรงพยาบาลพระอาจารย์ฝั้น อาจาโร </LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>11/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>TP10</REGISTER_CODE>
<REGISTER_FORMAT>ยาผง</REGISTER_FORMAT>
<REGISTER_IDA>14</REGISTER_IDA>
<REGISTER_NAME>กัญชา </REGISTER_NAME>
<REGISTER_PACKAGE>2</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ซอง</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>เป็นผลิตภัณฑ์กัญชาตำรับแผนไทย</REGISTER_REMARK>
<REGISTER_STRENGTH>กัญชา56.25กรัมในผงยา757.50กรัม</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>ยาอไภยสาลี อาจาโร เฮิร์บ</REGISTER_TRADER_NAME>
<REGISTER_TYPE>1</REGISTER_TYPE>
<REGISTER_UNIT>g/sachet</REGISTER_UNIT>
<ROAD>ติวานนท์</ROAD>
<SOI>ติวานนท์ 14</SOI>
<TEL>0 2590 3474</TEL>
<THMBLNM>ตลาดขวัญ</THMBLNM>
<ZIPCODE>11000</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>38 </ADDR>
<AMPHRNM>เมืองนนทบุรี</AMPHRNM>
<APPROVE_DATE>2019-07-08T00:00:00</APPROVE_DATE>
<CHNGWTNM>นนทบุรี</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>โรงพยาบาลพระอาจารย์ฝั้น อาจาโร </LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>11/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>TP11</REGISTER_CODE>
<REGISTER_FORMAT>ยาผง</REGISTER_FORMAT>
<REGISTER_IDA>15</REGISTER_IDA>
<REGISTER_NAME>กัญชา </REGISTER_NAME>
<REGISTER_PACKAGE>2.5</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ซอง</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>เป็นผลิตภัณฑ์กัญชาตำรับแผนไทย</REGISTER_REMARK>
<REGISTER_STRENGTH>ใบกัญชา20กรัมในผงยา75 กรัม</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>ยาแก้ลมแก้เส้น อาจาโร เฮิร์บ</REGISTER_TRADER_NAME>
<REGISTER_TYPE>1</REGISTER_TYPE>
<REGISTER_UNIT>g/sachet</REGISTER_UNIT>
<ROAD>ติวานนท์</ROAD>
<SOI>ติวานนท์ 14</SOI>
<TEL>0 2590 3474</TEL>
<THMBLNM>ตลาดขวัญ</THMBLNM>
<ZIPCODE>11000</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>38 </ADDR>
<AMPHRNM>เมืองนนทบุรี</AMPHRNM>
<APPROVE_DATE>2019-07-08T00:00:00</APPROVE_DATE>
<CHNGWTNM>นนทบุรี</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>โรงพยาบาลพระอาจารย์ฝั้น อาจาโร </LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>11/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>TP12</REGISTER_CODE>
<REGISTER_FORMAT>ยาผง</REGISTER_FORMAT>
<REGISTER_IDA>16</REGISTER_IDA>
<REGISTER_NAME>กัญชา </REGISTER_NAME>
<REGISTER_PACKAGE>1</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ซอง</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>เป็นผลิตภัณฑ์กัญชาตำรับแผนไทย</REGISTER_REMARK>
<REGISTER_STRENGTH>ก้านกัญชา15กรัมในผงยา570กรัม</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>ยาแก้โรคจิต อาจาโร เฮิร์บ</REGISTER_TRADER_NAME>
<REGISTER_TYPE>1</REGISTER_TYPE>
<REGISTER_UNIT>g/sachet</REGISTER_UNIT>
<ROAD>ติวานนท์</ROAD>
<SOI>ติวานนท์ 14</SOI>
<TEL>0 2590 3474</TEL>
<THMBLNM>ตลาดขวัญ</THMBLNM>
<ZIPCODE>11000</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>38 </ADDR>
<AMPHRNM>เมืองนนทบุรี</AMPHRNM>
<APPROVE_DATE>2019-07-08T00:00:00</APPROVE_DATE>
<CHNGWTNM>นนทบุรี</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>โรงพยาบาลพระอาจารย์ฝั้น อาจาโร </LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>11/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>TP13</REGISTER_CODE>
<REGISTER_FORMAT>ยาผง</REGISTER_FORMAT>
<REGISTER_IDA>17</REGISTER_IDA>
<REGISTER_NAME>กัญชา </REGISTER_NAME>
<REGISTER_PACKAGE>3.75</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ซอง</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>เป็นผลิตภัณฑ์กัญชาตำรับแผนไทย</REGISTER_REMARK>
<REGISTER_STRENGTH>กัญชา450กรัมในผงยา1820.63กรัม</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>ยาไพสาลี อาจาโร เฮิร์บ</REGISTER_TRADER_NAME>
<REGISTER_TYPE>1</REGISTER_TYPE>
<REGISTER_UNIT>g/sachet</REGISTER_UNIT>
<ROAD>ติวานนท์</ROAD>
<SOI>ติวานนท์ 14</SOI>
<TEL>0 2590 3474</TEL>
<THMBLNM>ตลาดขวัญ</THMBLNM>
<ZIPCODE>11000</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>38 </ADDR>
<AMPHRNM>เมืองนนทบุรี</AMPHRNM>
<APPROVE_DATE>2019-07-08T00:00:00</APPROVE_DATE>
<CHNGWTNM>นนทบุรี</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>โรงพยาบาลพระอาจารย์ฝั้น อาจาโร </LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>11/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>TP14</REGISTER_CODE>
<REGISTER_FORMAT>น้ำมัน</REGISTER_FORMAT>
<REGISTER_IDA>18</REGISTER_IDA>
<REGISTER_NAME>กัญชา </REGISTER_NAME>
<REGISTER_PACKAGE>45</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ซอง</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>เป็นผลิตภัณฑ์กัญชาตำรับแผนไทย</REGISTER_REMARK>
<REGISTER_STRENGTH>ใบกัญชา15กรัมในผงยา60กรัม</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>ยาทาริดสีดวงทวารหนักและโรคผิวหนัง อาจาโร เฮิร์บ</REGISTER_TRADER_NAME>
<REGISTER_TYPE>1</REGISTER_TYPE>
<REGISTER_UNIT>g/sachet</REGISTER_UNIT>
<ROAD>ติวานนท์</ROAD>
<SOI>ติวานนท์ 14</SOI>
<TEL>0 2590 3474</TEL>
<THMBLNM>ตลาดขวัญ</THMBLNM>
<ZIPCODE>11000</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>38 </ADDR>
<AMPHRNM>เมืองนนทบุรี</AMPHRNM>
<APPROVE_DATE>2019-07-08T00:00:00</APPROVE_DATE>
<CHNGWTNM>นนทบุรี</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>โรงพยาบาลพระอาจารย์ฝั้น อาจาโร </LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>11/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>TP15</REGISTER_CODE>
<REGISTER_FORMAT>ยาผง</REGISTER_FORMAT>
<REGISTER_IDA>19</REGISTER_IDA>
<REGISTER_NAME>กัญชา </REGISTER_NAME>
<REGISTER_PACKAGE>3.75</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ซอง</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>เป็นผลิตภัณฑ์กัญชาตำรับแผนไทย</REGISTER_REMARK>
<REGISTER_STRENGTH>กัญชา30กรัมในผงยา1388.75กรัม</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>ยาทำลายพระสุเมรุ อาจาโร เฮิร์บ</REGISTER_TRADER_NAME>
<REGISTER_TYPE>1</REGISTER_TYPE>
<REGISTER_UNIT>g/sachet</REGISTER_UNIT>
<ROAD>ติวานนท์</ROAD>
<SOI>ติวานนท์ 14</SOI>
<TEL>0 2590 3474</TEL>
<THMBLNM>ตลาดขวัญ</THMBLNM>
<ZIPCODE>11000</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>38 </ADDR>
<AMPHRNM>เมืองนนทบุรี</AMPHRNM>
<APPROVE_DATE>2019-07-08T00:00:00</APPROVE_DATE>
<CHNGWTNM>นนทบุรี</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>โรงพยาบาลพระอาจารย์ฝั้น อาจาโร </LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>11/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>TP16</REGISTER_CODE>
<REGISTER_FORMAT>ยาผง</REGISTER_FORMAT>
<REGISTER_IDA>20</REGISTER_IDA>
<REGISTER_NAME>กัญชา </REGISTER_NAME>
<REGISTER_PACKAGE>3</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ซอง</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>เป็นผลิตภัณฑ์กัญชาตำรับแผนไทย</REGISTER_REMARK>
<REGISTER_STRENGTH>กัญชา1กรัมในผงยา30กรัม</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>ยาทัพยาธิคุณ อาจาโร เฮิร์บ</REGISTER_TRADER_NAME>
<REGISTER_TYPE>1</REGISTER_TYPE>
<REGISTER_UNIT>g/sachet</REGISTER_UNIT>
<ROAD>ติวานนท์</ROAD>
<SOI>ติวานนท์ 14</SOI>
<TEL>0 2590 3474</TEL>
<THMBLNM>ตลาดขวัญ</THMBLNM>
<ZIPCODE>11000</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>-</ADDR>
<AMPHRNM>-</AMPHRNM>
<APPROVE_DATE>2019-01-01T00:00:00</APPROVE_DATE>
<CHNGWTNM>-</CHNGWTNM>
<EXP_DATE>2358-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>000000000</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ได้รับการยกเว้น ไม่ต้องมีใบอนุญาต</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>บริษัทเลิฟ เฮมพ์ ( ประเทศไทย) จำกัด</LICENSE_PLACE>
<LICENSE_TYPE>-</LICENSE_TYPE>
<LICENSE_TYPE_NAME>ได้รับการยกเว้น ไม่ต้องมีใบอนุญาต</LICENSE_TYPE_NAME>
<LOCATION_CODE>ได้รับการยกเว้น ไม่ต้องมีใบอนุญาต</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>Donate1</REGISTER_CODE>
<REGISTER_FORMAT>น้ำมันกัญชาหยดใต้ลิ้น</REGISTER_FORMAT>
<REGISTER_IDA>21</REGISTER_IDA>
<REGISTER_NAME>กัญชา</REGISTER_NAME>
<REGISTER_PACKAGE>10</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ขวด</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>
ผลิตภัณฑ์กัญชานี้ได้รับยกเว้นการรับรองตำรับจากสำนักงาน อย. เพื่อใช้สำหรับผู้ป่วยเฉพาะราย ภายใต้รูปแบบพิเศษของการเข้าถึงยา ( Special access scheme ) ต้องสั่งจ่ายโดยแพทย์ที่ผ่านการอบรมหลักสูตรการใช้กัญชาและสารสกัดจากกัญชาในทางการแพทย์จากกระทรวงสาธารณสุขและต้องได้รับการยินยอมจากผู้ป่วยหรือผู้ดูแลผู้ป่วย โดยการลงนามเป็นลายลักษณ์อักษรในเอกสารแสดงความยินยอม
</REGISTER_REMARK>
<REGISTER_STRENGTH>Cannabiidiol (CBD) 10%</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>น้ำมันกัญชา LOVE HEMP </REGISTER_TRADER_NAME>
<REGISTER_TYPE>2</REGISTER_TYPE>
<REGISTER_UNIT>ml</REGISTER_UNIT>
<ROAD>-</ROAD>
<SOI>-</SOI>
<TEL>-</TEL>
<THMBLNM>-</THMBLNM>
<ZIPCODE>-</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>2</ADDR>
<AMPHRNM>สาทร</AMPHRNM>
<APPROVE_DATE>2019-07-08T00:00:00</APPROVE_DATE>
<CHNGWTNM>กรุงเทพมหานคร</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>องค์การเภสัชกรรม</LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>8/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>SAS5</REGISTER_CODE>
<REGISTER_FORMAT>น้ำมันกัญชาหยดใต้ลิ้น</REGISTER_FORMAT>
<REGISTER_IDA>22</REGISTER_IDA>
<REGISTER_NAME>กัญชา </REGISTER_NAME>
<REGISTER_PACKAGE>30</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ขวด</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>
ผลิตภัณฑ์กัญชานี้ได้รับยกเว้นการรับรองตำรับจากสำนักงาน อย. เพื่อใช้สำหรับผู้ป่วยเฉพาะราย ภายใต้รูปแบบพิเศษของการเข้าถึงยา ( Special access scheme ) ต้องสั่งจ่ายโดยแพทย์ที่ผ่านการอบรมหลักสูตรการใช้กัญชาและสารสกัดจากกัญชาในทางการแพทย์จากกระทรวงสาธารณสุขและต้องได้รับการยินยอมจากผู้ป่วยหรือผู้ดูแลผู้ป่วย โดยการลงนามเป็นลายลักษณ์อักษรในเอกสารแสดงความยินยอม
</REGISTER_REMARK>
<REGISTER_STRENGTH>CBD 100 mg/ml</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>น้ำมันกัญชาหยอดใต้ลิ้น </REGISTER_TRADER_NAME>
<REGISTER_TYPE>2</REGISTER_TYPE>
<REGISTER_UNIT>ml</REGISTER_UNIT>
<ROAD>นราธิวาสราชนครินทร์</ROAD>
<SOI>-</SOI>
<TEL>0 2676 2727</TEL>
<THMBLNM>ทุ่งวัดดอน</THMBLNM>
<ZIPCODE>10120</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>23 </ADDR>
<AMPHRNM>ทวีวัฒนา</AMPHRNM>
<APPROVE_DATE>2019-07-08T00:00:00</APPROVE_DATE>
<CHNGWTNM>กรุงเทพมหานคร</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>โรงพยาบาลเจ้าพระยาอภัยภูเบศร</LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>10/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>8</MU>
<REGISTER_CODE>SAS6</REGISTER_CODE>
<REGISTER_FORMAT>น้ำมันกัญชาหยดใต้ลิ้น</REGISTER_FORMAT>
<REGISTER_IDA>23</REGISTER_IDA>
<REGISTER_NAME>กัญชา</REGISTER_NAME>
<REGISTER_PACKAGE>5</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ขวด</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>
ผลิตภัณฑ์กัญชานี้ได้รับยกเว้นการรับรองตำรับจากสำนักงาน อย. เพื่อใช้สำหรับผู้ป่วยเฉพาะราย ภายใต้รูปแบบพิเศษของการเข้าถึงยา ( Special access scheme ) ต้องสั่งจ่ายโดยแพทย์ที่ผ่านการอบรมหลักสูตรการใช้กัญชาและสารสกัดจากกัญชาในทางการแพทย์จากกระทรวงสาธารณสุขและต้องได้รับการยินยอมจากผู้ป่วยหรือผู้ดูแลผู้ป่วย โดยการลงนามเป็นลายลักษณ์อักษรในเอกสารแสดงความยินยอม
</REGISTER_REMARK>
<REGISTER_STRENGTH>CBD 10%W/V ( 100 mg/ml) (2.94 mg/drop)</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>น้ำมันกัญชาหยอดใต้ลิ้น </REGISTER_TRADER_NAME>
<REGISTER_TYPE>2</REGISTER_TYPE>
<REGISTER_UNIT>ml</REGISTER_UNIT>
<ROAD>พุทธมณฑลสาย 4</ROAD>
<SOI>-</SOI>
<TEL>0 2441 6100</TEL>
<THMBLNM>ทวีวัฒนา</THMBLNM>
<ZIPCODE>10170</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>2</ADDR>
<AMPHRNM>สาทร</AMPHRNM>
<APPROVE_DATE>2019-01-11T00:00:00</APPROVE_DATE>
<CHNGWTNM>กรุงเทพมหานคร</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>294600001</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>องค์การเภสัชกรรม</LICENSE_PLACE>
<LICENSE_TYPE>041</LICENSE_TYPE>
<LICENSE_TYPE_NAME>จำหน่าย</LICENSE_TYPE_NAME>
<LOCATION_CODE>8/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>-</MU>
<REGISTER_CODE>SAS7</REGISTER_CODE>
<REGISTER_FORMAT>น้ำมันกัญชาหยดใต้ลิ้น</REGISTER_FORMAT>
<REGISTER_IDA>24</REGISTER_IDA>
<REGISTER_NAME>กัญชา</REGISTER_NAME>
<REGISTER_PACKAGE>30</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ขวด</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>
ผลิตภัณฑ์กัญชานี้ได้รับยกเว้นการรับรองตำรับจากสำนักงาน อย. เพื่อใช้สำหรับผู้ป่วยเฉพาะราย ภายใต้รูปแบบพิเศษของการเข้าถึงยา ( Special access scheme ) ต้องสั่งจ่ายโดยแพทย์ที่ผ่านการอบรมหลักสูตรการใช้กัญชาและสารสกัดจากกัญชาในทางการแพทย์จากกระทรวงสาธารณสุขและต้องได้รับการยินยอมจากผู้ป่วยหรือผู้ดูแลผู้ป่วย โดยการลงนามเป็นลายลักษณ์อักษรในเอกสารแสดงความยินยอม
</REGISTER_REMARK>
<REGISTER_STRENGTH>CBD 100 mg/ml (CBD4mg/drop)</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>GPO CBD </REGISTER_TRADER_NAME>
<REGISTER_TYPE>2</REGISTER_TYPE>
<REGISTER_UNIT>ml</REGISTER_UNIT>
<ROAD>นราธิวาสราชนครินทร์</ROAD>
<SOI>-</SOI>
<TEL>0 2676 2727</TEL>
<THMBLNM>ทุ่งวัดดอน</THMBLNM>
<ZIPCODE>10120</ZIPCODE>
</MAS_RECIPE>
<MAS_RECIPE>
<ADDR>117</ADDR>
<AMPHRNM>คลองหลวง</AMPHRNM>
<APPROVE_DATE>2019-08-01T00:00:00</APPROVE_DATE>
<CHNGWTNM>ปทุมธานี</CHNGWTNM>
<EXP_DATE>2019-12-31T00:00:00</EXP_DATE>
<GTIN>-</GTIN>
<LICENSE_OBJECT_CODE>293600002</LICENSE_OBJECT_CODE>
<LICENSE_OBJECT_NAME>ผลิต (แปรรูปหรือสกัด) ซึ่งยาเสพติดให้โทษในประเภท 5</LICENSE_OBJECT_NAME>
<LICENSE_PLACE>
กองพัฒนายาแผนไทยและสมุนไพร การแพทย์แผนไทยและการแพทย์ทางเลือก
</LICENSE_PLACE>
<LICENSE_TYPE>032</LICENSE_TYPE>
<LICENSE_TYPE_NAME>ผลิต</LICENSE_TYPE_NAME>
<LOCATION_CODE>13/2562</LOCATION_CODE>
<MAX_DISPENSE_UNIT>100</MAX_DISPENSE_UNIT>
<MU>9</MU>
<REGISTER_CODE>RES1</REGISTER_CODE>
<REGISTER_FORMAT>น้ำมันกัญชา</REGISTER_FORMAT>
<REGISTER_IDA>25</REGISTER_IDA>
<REGISTER_NAME>กัญชา</REGISTER_NAME>
<REGISTER_PACKAGE>5</REGISTER_PACKAGE>
<REGISTER_PACKAGE_UNIT>ขวด</REGISTER_PACKAGE_UNIT>
<REGISTER_REMARK>
ผลิตภัณฑ์กัญชาที่ผลิตขึ้นภายใต้โครงการติดตามลักษณะการใช้และคุณภาพชีวิตของผู้ใช้น้ำมันกัญชาในทางการแพทย์แผนไทยและการแพทย์ทางเลือก ที่ผ่านการพิจารณาคณะกรรมการจริยธรรมการวิจัยในคน กระทรวงสาธารณสุข
</REGISTER_REMARK>
<REGISTER_STRENGTH>สารสกัดกัญชาในน้ำมันมะพร้าว 10% ของน้ำมันกัญชาแห้ง</REGISTER_STRENGTH>
<REGISTER_TRADER_NAME>
น้ำมันกัญชา ( ตำรับหมอเดชา ) DTAM GANJA OIL (DEJA FORMULA)
</REGISTER_TRADER_NAME>
<REGISTER_TYPE>1</REGISTER_TYPE>
<REGISTER_UNIT>ml</REGISTER_UNIT>
<ROAD>พหลโยธิน</ROAD>
<SOI>-</SOI>
<TEL>0 2564 7889</TEL>
<THMBLNM>คลองหนึ่ง</THMBLNM>
<ZIPCODE>12120</ZIPCODE>
</MAS_RECIPE>
</ArrayOfMAS_RECIPE>
XML;
?>